config/routes.rb
Rails.application.routes.draw do
  root 'sites#index'
  resources :sites
  resources :posts
  resources :comments
  resources :authors
  get 'veiws/' => 'veiws#show'
  get 'webscanner/' => 'webscanner#show'
  post 'webscanner/scan' => 'webscanner#scan_test'
  post 'webscanner/load' => 'webscanner#load_test'

end

app/models/author.rb
class Author < ActiveRecord::Base
    # has_many :posts
    has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    is_impressionable
    belongs_to :post
    belongs_to :author
    # belongs_to :site, through: :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    is_impressionable
    belongs_to :site
    has_many :comments
    
    def test1
        comments.size
    end
    
    def comment_rate1
       comments.group_by_day(:comment_time).count.map {|k, v| [((k.to_datetime().to_date)-post_time.to_date).to_i, v] }
    end

end

app/models/site.rb
class Site < ActiveRecord::Base
    is_impressionable
    has_many :posts
    has_many :comments, through: :posts
    
    def name
        self.sitename
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  
  def remove_empty(table)
    # removes entries in table with a 0 value
    table.select {|k,v| v!=0 }
  end
  helper_method :remove_empty
  
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    def show
        @author=Author.find(params[:id])
        @comments=@author.comments
    end
    
    def index
        @authors=Author.all
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    impressionist
    
    def show
        @comment=Comment.find(params[:id])
    end
end

app/controllers/metadata_creation_controller.rb
class MetadataCreationController < ApplicationController
    
    def self.generate_authors
        # Creates Authors from the author names of posts and comments.
        Post.all.each do |el|
            if Author.find_by_name(el.post_author_name)==nil
                Author.create(name: el.post_author_name)
            end
        end
        Comment.all.each do |el|
            if Author.find_by_name(el.comment_author_name)==nil
                Author.create(name: el.comment_author_name)
            end
        end
        get_author_ids
    end
    
    def self.get_author_ids
        # Adds an author_id for author lookup to posts and comments.
        Post.all.each do |el|
            if Author.find_by_name(el.post_author_name)!=nil
                el.author_id=Author.find_by_name(el.post_author_name).id
            end
        end
        Comment.all.each do |el|
            if Author.find_by_name(el.comment_author_name)!=nil
                el.author_id=Author.find_by_name(el.comment_author_name).id
            end
        end
    end
    
    def self.get_days_after
        # Adds a days_after element to comments mesuring how long after the post the comment was made.
        Comment.all.each do |el|
             el.days_after=((el.comment_time.to_date)-(el.post.post_time.to_date)).to_i
             el.save
        end
        5
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    impressionist
    
    def show
        @post=Post.find(params[:id]).sort_by(&:title)  
    end
    
    def index
        @posts=Post.all
    end
end

app/controllers/site_stats_controller.rb
class SiteStatsController < ApplicationController
    def overview
        @sites=Site.all
    end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
    impressionist
    
    def show
        @site=Site.find(params[:id])
        @posts=@site.posts.sort_by(&:title)
    end
    
    def index
        @sites=Site.all
        @chart1=@sites.map { |site| {name: site.sitename, data: first_10_days(site.comments.group("days_after").count)}}
        @ratios=@sites.map { |site| [site.sitename, char_ratio(site)]}
    end
    
    def first_10_days(data)
        # 
        site_rate=Hash.new(0)
        (0..9).each {|n| site_rate[n]=0 }
        site_rate.each {|key, count| (site_rate[key] += data[key]) if data.has_key?(key)}
        site_rate.each {|key, value| site_rate[key]=value.to_i}
        site_rate
    end
    
    def char_ratio(site)
        # Returns the comparative ratio of the length of text of all the comment to the lenge of the posts.
        site.comments.sum('comment_size')/(1.0*site.posts.sum('post_size'))
    end
    
end

app/controllers/veiws_controller.rb
class VeiwsController < ApplicationController
    
    def show
        @sites=Site.all
        @posts=Post.all
    end
end

app/controllers/webscanner_controller.rb
class WebscannerController < ApplicationController
    
    
    def show
        @sites=Site.all.size
        @posts=Post.all.size
        @comments=Comment.all.count
        @authors=Author.all.count
    end
    
    def scan_test
        # Controler action for intiating the python webscraper
        run_scan
        redirect_to "/webscanner"
    end
    
    def load_test
        # Controler action for load webscrapper data
        system("rake db:reset")
        load_data
        redirect_to "/webscanner"
    end
    
    def run_scan
        # Runs the webscrapper
        # Dir.chdir("BlogScraper") do
        #     system('python3 "post scanner.py"')
        #     system('python3 "parser.py"') 
        # end
        # File.write("scan_input.txt", scan_input)
        # system("python webscanner.py")
    end
    
    def self.load_data
        # Loads the the text files outputed by the webscrapper into the database
        sitelist=eval(File.read("BlogScraper//sitelist.txt"))
        sitelist.each do |site|
            if Site.find_by_sitename(site)==nil
                Site.create(sitename: site)
            end
	        posts=eval(File.read("BlogScraper//site data//#{site}//posts.txt"))
	        posts.each do |el|
	            unless el[2]==""
	    	        Post.create(site_id: Site.find_by_sitename(el[0]).id, html_id: el[1], title: el[2], post_author_name: el[3],
	    	        post_time: el[4], text: el[5], post_size: el[5].size)
	    	    end
	        end
	        comments=eval(File.read("BlogScraper//site data//#{site}//comments.txt"))
	        print "test"
	        print "/n"
	        comments.each do |el|
	            comment_post_id=Post.where("site_id = #{Site.find_by_sitename(el[0]).id} AND title = '#{el[1]}'")[0].id
		        Comment.create(post_id: comment_post_id, html_id: el[2], comment_author_name: el[3], comment_time: el[4],
		        depth: el[5], text: el[6].each_char.select{|c| c.bytes.count < 4 }.join(''), comment_size: el[6].size)
            end
        end
        MetadataCreationController.generate_authors
        MetadataCreationController.get_days_after
        # posts=eval(File.read("post_test.html"))
        # posts.each do |el|
        #     Post.create(html_id: el[0], title: el[1], author: el[2], time: el[3], text: el[4])
        # end
        # comments=eval(File.read("comments_test.html"))
        # comments.each do |el|
        #     Comment.create(html_id: el[2], author: el[3], time: el[4], depth: el[5], text: el[6])
        # end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/metadata_creation_helper.rb
module MetadataCreationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/site_stats_helper.rb
module SiteStatsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/veiws_helper.rb
module VeiwsHelper
end

app/helpers/webscanner_helper.rb
module WebscannerHelper
end

app/views/authors/index.html.erb
<ul>
  <% @Authors.each do |el| %>
    <li>
      <%= link_to "#{el.name}", author_url(el) %>
      <%= "#{el.name} #{site.comments.count}" %>
    </li>
  <% end %>
</ul>

app/views/authors/show.html.erb
<%= "#{@author.name} " %>
<%= "Comments: #{@author.comments.count}" %>





<ul>
  <% @comments.each do |el| %>
    <li>
      <%= link_to "#{el.post.title}", post_url(post) %>
      <%= "#{post.comments.count}" %>
      <%= column_chart post.comments.group(:author).count %>
    </li>
  <% end %>
</ul>

app/views/posts/index.html.erb
<ul>
  <% @posts.each do |el| %>
    <li>
      <%= "Post title" %>
      <%= link_to "#{el.title}", post_url(el) %>
      <%= column_chart el.comments.group_by_month(:comment_time).count %>
      <%= "Comments by" %>
      <%= column_chart el.comments.group(:comment_author_name).having("COUNT(*) > 10").count %>
    </li>
  <% end %>
</ul>

app/views/posts/show.html.erb
<%= "Site: " %>
<%= link_to "#{@post.site.sitename}", site_url(@post.site) %>

<%= "Comments: #{@post.comments.count}" %>

<li>
  <%= "Comment replies" %>
  <%= @post.comments.where("2 > 1").count %>
</li>

<li>
  <%= "Comments by author" %>
  <%= column_chart @post.comments.group(:comment_author_name).count %>
</li>
<li>
  <%= "Comments by day" %>
  <%= column_chart @post.comments.group_by_day(:comment_time).count %>
</li>

<li>
  <%= "Raito of comments to post text " %>
  <%=  "#{@post.comments.sum('comment_size')/(1.0*@post.post_size)}" %>
</li>

app/views/site_stats/overview.html.erb
<ul>
  <% @sites.each do |site| %>
    <li>
      <%= "#{site.name} #{site.posts.count}" %>
    </li>
  <% end %>
</ul>

app/views/sites/index.html.erb
<ul>
  
  
  <h2>Comment Rate for First 10 Days</h2>
  <%= column_chart @chart1 %>
  
  <h2></h2>
  
  <h2>Ratio of Post Length to Comments</h2>
  <div class="row">
  <% @ratios.each do |ratio| %>
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-6">
      <%= "#{ratio[0]} percent of text of Posts and Comments" %>
      <%= pie_chart [["Posts",100*(1/(ratio[1]+1))],["Comments",100*(ratio[1]/(ratio[1]+1))]] %>
    </div>
  <% end %>
  </div>
  
  <h2></h2>


  <h2>Individual Sites</h2>
  <% @sites.each do |site| %>
      <h3>
      <%= link_to "#{site.sitename.capitalize}", site_url(site) %>
      <%= "Posts: #{site.posts.count} Comments: #{site.comments.count}  " %>
      
      </h3>
  <% end %>
</ul>

app/views/sites/show.html.erb
<h2><%= "#{@site.sitename}   Posts: #{@site.posts.count} Comments: #{@site.comments.count}" %></h2>




<h2>Individual Posts</h2>
<% @posts.each do |post| %>
  <h3>
    <%= link_to "#{post.title}", post_url(post) %>
    <%= "Comments: #{post.comments.count}" %>
  </h3>
<% end %>




  <h2><%= "Comments by day" %></h2>
  <%= column_chart remove_empty(@site.comments.group_by_day(:comment_time).count).map {|k, v| [k.to_datetime().to_date, v] } %>


  <h2><%= "Commenters" %></h2>
  <%= column_chart remove_empty(@site.comments.group(:comment_author_name).count) %>

  <h2><%= "Commenters with 10+ comments" %></h2>
  <%= column_chart remove_empty(@site.comments.group(:comment_author_name).having("COUNT(*) > 10").size) %>

app/views/veiws/show.html.erb
<ul>
  <% @sites.each do |site| %>
    <li>
      <%= "Site Name: #{site.name} Veiws: #{site.impressionist_count}  " %>
    </li>
  <% end %>
</ul>

<ul>
  <% @posts.each do |el| %>
    <li>
      <%= "Post Name: #{el.title} Veiws: #{el.impressionist_count}  " %>
    </li>
  <% end %>
</ul>

app/views/webscanner/show.html.erb
<form action="/webscanner/scan" method="post">
  <input type="submit" value="Scan Sites (inactive)">
</form>


<form action="/webscanner/load" method="post">
  <input type="submit" value="Save to Database">
</form>

<li>
<%= "#{@sites}" %>
</li>
<li>
<%= "#{@posts}" %>
</li>
<li>
<%= "#{@comments} " %>
</li>
<li>
<%= "#{@authors} " %>
</li>